version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ConstructShop
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db

  www:
    build: "./docker-www"
    volumes:
      - "./www:/var/www/html"
    ports:
      - 80:80
